import { expect, test } from "@playwright/test";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const password = "Orbis-browser-test-2026!";
const apiOrigin = "http://127.0.0.1:9311";

test("personal writing, team discussion and a versioned documentation site work together", async ({ page, browser, request }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/setup");
  await page.getByLabel("显示名称").fill("Orbis 团队");
  await page.getByLabel("邮箱").fill("owner@example.com");
  await page.getByLabel("密码", { exact: true }).fill(password);
  await page.getByRole("button", { name: "创建并进入工作空间" }).click();
  await expect(page).toHaveURL(/\/documents$/);
  await page.getByRole("link", { name: "新建笔记本", exact: true }).click();
  await page.getByRole("button", { name: "新建笔记本", exact: true }).click();
  await page.getByLabel("笔记本名称").fill("产品指南");
  await page.getByRole("button", { name: "创建笔记本", exact: true }).click();
  await expect(page).toHaveURL(/\/collections\//);
  const notebookId = page.url().split("/").pop()!;
  await page.getByRole("region", { name: "主工作区", exact: true }).getByRole("button", { name: "新建文档", exact: true }).click();
  await expect(page).toHaveURL(/\/documents\/[0-9a-f-]+$/);
  const noteId = page.url().split("/").pop()!;
  await page.getByRole("textbox", { name: "文档标题" }).fill("欢迎使用 Orbis");
  const editor = page.locator('[contenteditable="true"]').first();
  await expect(editor).toBeVisible();
  await editor.fill("让知识被找到，让协作更轻松。");
  await expect(page.getByText("已保存", { exact: true })).toBeVisible();
  const token = await page.evaluate(() => JSON.parse(localStorage.getItem("orbis.auth")!).accessToken as string);
  const headers = { Authorization: `Bearer ${token}` };
  await expect.poll(async () => (await (await request.get(`${apiOrigin}/notes/${noteId}/content`, { headers })).json()).data.plain_text).toContain("让知识被找到");

  await page.getByRole("button", { name: "评论与历史", exact: true }).click();
  await page.getByLabel("新评论", { exact: true }).fill("这一版欢迎页可以进入发布预览。");
  await page.getByRole("button", { name: "发表评论", exact: true }).click();
  await expect(page.getByText("这一版欢迎页可以进入发布预览。", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "历史版本", exact: true }).click();
  await page.getByRole("button", { name: "查看版本 1", exact: true }).click();
  await expect(page.getByRole("heading", { name: "版本 1 预览" })).toBeVisible();
  await page.getByRole("button", { name: "关闭评论与历史" }).click();

  const imported = await request.post(`${apiOrigin}/notes/import/markdown`, { headers, data: { notebook_id: notebookId, title: "快速开始", markdown: "# 快速开始\n\n从记录想法到公开分享，用一份内容连接个人与团队。\n\n## 组织你的知识\n\n创建笔记本，将相关文档放在一起。你可以随时调整标题和目录。\n\n## 与团队一起完善\n\n- 邀请成员进入工作空间\n- 用评论讨论内容\n- 在历史中查看与恢复正文\n\n## 发布一个站点\n\n```text\n选择文档 → 组织目录 → 预览 → 发布\n```\n\n| 使用场景 | 读者获得什么 |\n| --- | --- |\n| 知识站 | 有结构的知识分享 |\n| 产品手册 | 清晰的使用指南 |\n| 帮助中心 | 可检索的问题答案 |\n\n> 内部草稿可以持续修改，读者看到的是你确认发布的版本。" } });
  expect(imported.status()).toBe(201);

  await page.goto("/sites");
  await page.getByRole("button", { name: "创建站点", exact: true }).click();
  await page.getByLabel("站点名称", { exact: true }).fill("Orbis 知识指南");
  await page.getByLabel("站点路径", { exact: false }).fill("orbis-guide");
  await page.getByLabel("站点简介", { exact: true }).fill("记录、协作与发布，让团队知识持续生长。");
  await page.getByLabel("站点场景", { exact: false }).selectOption("handbook");
  await page.getByRole("button", { name: "创建并选择文档" }).click();
  await expect(page).toHaveURL(/\/sites\/[0-9a-f-]+$/);
  const siteId = page.url().split("/").pop()!;
  await page.getByRole("button", { name: /欢迎使用 Orbis.*让知识被找到/ }).click();
  await page.getByRole("button", { name: /快速开始.*从记录想法/ }).click();
  await page.getByLabel("第 1 篇页面路径").fill("welcome");
  await page.getByLabel("第 2 篇页面路径").fill("quickstart");
  await page.getByLabel("第 1 篇分组").fill("开始使用");
  await page.getByLabel("第 2 篇分组").fill("开始使用");
  await page.getByRole("button", { name: "保存设置", exact: true }).click();
  await expect(page.getByText("设置已保存", { exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("site-management.png"), fullPage: true });
  await page.getByRole("button", { name: "预览", exact: true }).click();
  await expect(page.getByText(/发布预览 ·/)).toBeVisible();
  await expect(page.getByRole("heading", { name: "欢迎使用 Orbis", exact: true })).toBeVisible();
  await page.getByRole("link", { name: "← 返回发布管理" }).click();
  await page.getByRole("button", { name: "发布站点", exact: true }).click();
  await page.getByRole("button", { name: "确认发布", exact: true }).click();
  await expect(page.getByText("站点已发布，读者现在可以访问新版本。", { exact: true })).toBeVisible();

  const guest = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const reader = await guest.newPage();
  await reader.goto("http://127.0.0.1:9310/s/orbis-guide/quickstart");
  await expect(reader.getByRole("heading", { name: "快速开始", level: 1 })).toBeVisible();
  await expect(reader.getByRole("table")).toContainText("产品手册");
  await reader.screenshot({ path: testInfo.outputPath("public-desktop.png"), fullPage: true });
  await reader.getByRole("searchbox", { name: "搜索文档" }).fill("欢迎");
  await expect(reader.getByLabel("搜索结果")).toContainText("欢迎使用 Orbis");
  await reader.getByRole("searchbox", { name: "搜索文档" }).fill("");
  await reader.getByRole("button", { name: "切换深色主题" }).click();
  await expect(reader.locator(".site-reader")).toHaveAttribute("data-theme", "dark");
  await reader.screenshot({ path: testInfo.outputPath("public-dark.png"), fullPage: true });
  await reader.setViewportSize({ width: 390, height: 844 });
  await reader.getByRole("button", { name: "打开站点导航" }).click();
  await reader.getByRole("navigation", { name: "站点导航", exact: true }).getByRole("link", { name: "欢迎使用 Orbis", exact: true }).click();
  await expect(reader.getByRole("heading", { name: "欢迎使用 Orbis", level: 1 })).toBeVisible();
  expect(await reader.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await reader.screenshot({ path: testInfo.outputPath("public-mobile.png"), fullPage: true });

  await page.goto(`/documents/${noteId}`);
  await page.locator('[contenteditable="true"]').first().fill("未发布的新内容，等待团队确认。");
  await expect.poll(async () => (await (await request.get(`${apiOrigin}/notes/${noteId}/content`, { headers })).json()).data.plain_text).toContain("未发布的新内容");
  await reader.reload();
  await expect(reader.getByText("让知识被找到，让协作更轻松。", { exact: true })).toBeVisible();
  await expect(reader.getByText("未发布的新内容", { exact: false })).toHaveCount(0);
  await page.goto(`/sites/${siteId}`);
  await page.getByRole("button", { name: "发布站点", exact: true }).click();
  await page.getByRole("button", { name: "确认发布", exact: true }).click();
  await expect(page.getByText("站点已发布，读者现在可以访问新版本。", { exact: true })).toBeVisible();
  await reader.reload();
  await expect(reader.getByText("未发布的新内容，等待团队确认。", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "切换到此版本", exact: true }).click();
  await page.getByRole("button", { name: "确认操作", exact: true }).click();
  await expect(page.getByText("已切换公开版本，内部文档保持当前内容。", { exact: true })).toBeVisible();
  await reader.reload();
  await expect(reader.getByText("让知识被找到，让协作更轻松。", { exact: true })).toBeVisible();

  await page.goto("/settings/members");
  await page.getByLabel("邮箱", { exact: true }).fill("reader@example.com");
  await page.getByRole("combobox").first().selectOption("normal");
  await page.getByRole("button", { name: "发送邀请", exact: true }).click();
  await expect(page.getByText("reader@example.com", { exact: true })).toBeVisible();
  const outbox = join(process.env.ORBIS_E2E_DIR!, "outbox");
  const invitation = readdirSync(outbox).map((file) => JSON.parse(readFileSync(join(outbox, file), "utf8"))).find((mail) => mail.recipient === "reader@example.com");
  const memberContext = await browser.newContext();
  const member = await memberContext.newPage();
  await member.goto(invitation.accept_url);
  await member.getByLabel("显示名称", { exact: true }).fill("协作成员");
  await member.getByLabel("设置密码", { exact: true }).fill(password);
  await member.getByRole("button", { name: "确认加入", exact: true }).click();
  await member.getByRole("button", { name: "前往登录", exact: true }).click();
  await member.getByLabel("邮箱", { exact: true }).fill("reader@example.com");
  await member.getByLabel("密码", { exact: true }).fill(password);
  await member.getByRole("button", { name: "登录 Orbis", exact: true }).click();
  await expect(member).toHaveURL(/\/documents$/);
  await member.goto(`http://127.0.0.1:9310/documents/${noteId}`);
  await expect(member.getByRole("textbox", { name: "文档标题" })).toHaveAttribute("readonly", "");
  await member.getByRole("button", { name: "评论与历史", exact: true }).click();
  await member.getByLabel("新评论", { exact: true }).fill("我已经检查，可以继续完善内容。");
  await member.getByRole("button", { name: "发表评论", exact: true }).click();
  await expect(member.getByText("我已经检查，可以继续完善内容。", { exact: true })).toBeVisible();
  await member.getByRole("button", { name: "历史版本", exact: true }).click();
  await member.getByRole("button", { name: "查看版本 1", exact: true }).click();
  await expect(member.getByRole("button", { name: "恢复此版本" })).toHaveCount(0);
  await memberContext.close();

  await page.goto(`/documents/${noteId}`);
  await page.getByRole("button", { name: "评论与历史", exact: true }).click();
  await page.getByRole("button", { name: "历史版本", exact: true }).click();
  await page.getByRole("button", { name: "查看版本 2", exact: true }).click();
  await page.getByRole("button", { name: "恢复此版本", exact: true }).click();
  await expect(page.getByRole("status", { name: "恢复结果" })).toContainText("已恢复为新版本");
  await page.getByRole("button", { name: "关闭评论与历史" }).click();
  await expect(page.locator('[contenteditable="true"]').first()).toContainText("让知识被找到，让协作更轻松。");
  const history = await (await request.get(`${apiOrigin}/notes/${noteId}/revisions`, { headers })).json();
  const previousDraft = history.data.items.find((item: { content_version: number }) => item.content_version === 3);
  const retained = await (await request.get(`${apiOrigin}/notes/${noteId}/revisions/${previousDraft.id}`, { headers })).json();
  expect(retained.data.plain_text).toContain("未发布的新内容");
  await page.screenshot({ path: testInfo.outputPath("workspace-editor.png"), fullPage: true });

  const archiveEditor = page.locator('[contenteditable="true"]').first();
  await archiveEditor.click();
  await archiveEditor.press("ControlOrMeta+End");
  await archiveEditor.press("Enter");
  await archiveEditor.pressSequentially("归档前的最后修改。");
  await page.getByRole("button", { name: "归档文档", exact: true }).click();
  await expect(page).toHaveURL(/\/collections\//);
  await page.goto("/documents/archive");
  await page.getByRole("button", { name: "恢复 欢迎使用 Orbis", exact: true }).click();
  await expect(page.getByRole("button", { name: "恢复 欢迎使用 Orbis", exact: true })).toHaveCount(0);
  expect((await (await request.get(`${apiOrigin}/notes/${noteId}/content`, { headers })).json()).data.plain_text).toContain("归档前的最后修改。");
  await reader.reload();
  await expect(reader.getByText("归档前的最后修改。", { exact: true })).toHaveCount(0);
  await page.goto("/documents/search");
  await page.getByRole("searchbox", { name: "搜索文档" }).fill("让知识被找到");
  await expect(page.getByRole("link", { name: /欢迎使用 Orbis/ })).toBeVisible();

  await page.goto("/documents/collections");
  await page.getByRole("button", { name: "新建笔记本", exact: true }).click();
  await page.getByLabel("笔记本名称").fill("Markdown 交换验证");
  await page.getByRole("button", { name: "创建笔记本", exact: true }).click();
  await expect(page).toHaveURL(/\/collections\//);
  const exchangeNotebook = page.url();
  const chooserPromise = page.waitForEvent("filechooser");
  await page.getByRole("button", { name: "导入 Markdown", exact: true }).click();
  const chooser = await chooserPromise;
  await chooser.setFiles({ name: "交换格式.md", mimeType: "text/markdown", buffer: Buffer.from("# 交换格式\n\nMarkdown 往返保留正文。\n\n- 第一项\n- 第二项\n") });
  await expect(page).toHaveURL(/\/documents\/[0-9a-f-]+$/);
  await expect(page.getByRole("textbox", { name: "文档标题" })).toHaveValue("交换格式");
  await expect(page.locator('[contenteditable="true"]').first()).toContainText("Markdown 往返保留正文。");
  await page.goto(exchangeNotebook);
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "导出全部", exact: true }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("交换格式.md");
  expect(readFileSync((await download.path())!, "utf8")).toContain("Markdown 往返保留正文。");

  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`/documents/${noteId}`);
  await expect(page.getByRole("textbox", { name: "文档标题" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole("button", { name: "打开主导航", exact: true }).click();
  await page.getByRole("navigation", { name: "业务板块", exact: true }).getByRole("link", { name: "站点", exact: true }).click();
  await expect(page).toHaveURL(/\/sites$/);
  await expect(page.getByRole("button", { name: "打开主导航", exact: true })).toHaveAttribute("aria-expanded", "false");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("workspace-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });

  await page.goto(`/sites/${siteId}`);
  await page.getByRole("button", { name: "撤回站点", exact: true }).click();
  await page.getByRole("button", { name: "确认操作", exact: true }).click();
  await expect(page.getByText("站点已撤回，公开入口现已关闭。", { exact: true })).toBeVisible();
  await reader.reload();
  await expect(reader.getByRole("heading", { name: "站点尚未发布或已撤回" })).toBeVisible();
  await guest.close();
  expect(errors).toEqual([]);
});
