from __future__ import annotations

import asyncio
import shutil
from pathlib import Path

import orbis_user_api.models  # noqa: F401
import pytest
from alembic import command
from alembic.config import Config
from orbis_user_api.core.settings import Settings
from orbis_user_api.db.base import Base
from sqlalchemy import inspect
from sqlalchemy.ext.asyncio import create_async_engine

SERVICE_ROOT = Path(__file__).resolve().parents[2]


def test_autogenerated_revision_upgrades_without_manual_import_repairs(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    migrations = tmp_path / "migrations"
    (migrations / "versions").mkdir(parents=True)
    for filename in ("env.py", "script.py.mako"):
        shutil.copyfile(SERVICE_ROOT / "migrations" / filename, migrations / filename)
    settings = Settings(
        _env_file=None,
        database_url=f"sqlite+aiosqlite:///{tmp_path / 'migration.db'}",
        database_schema=None,
        storage_dir=tmp_path / "storage",
    )
    monkeypatch.setattr("orbis_user_api.core.settings.Settings", lambda: settings)
    config = Config()
    config.set_main_option("script_location", str(migrations))
    command.revision(config, message="Generated model schema", autogenerate=True)

    # Execute the generated artifact unchanged, including custom GUID columns.
    command.upgrade(config, "head")
    command.check(config)

    async def table_names() -> set[str]:
        engine = create_async_engine(settings.database_url)
        try:
            async with engine.connect() as connection:
                return set(
                    await connection.run_sync(
                        lambda conn: inspect(conn).get_table_names()
                    )
                )
        finally:
            await engine.dispose()

    assert asyncio.run(table_names()) == set(Base.metadata.tables) | {"alembic_version"}
    command.downgrade(config, "base")
    assert asyncio.run(table_names()) == {"alembic_version"}
